### PR TITLE
updating the readme.md file and adding the requirements.txt file

### PR DESCRIPTION
**Pull request by ceasor-elvis**
Added the `requirements.txt` file.
Removed the first statement in the `readme.md` file which was not necessary, and also updated the `git clone` paragraph adding the user name. Updated the Usage part adding more appropriate instructions.

### CODE REVIEW

**Comment by Prince07746** [comment]
Thanks for the update elvis

**Comment by ceasor-elvis** [comment]
You are welcome.
I am also looking forward to updating the code because I have been learning
machine learning and I think I grasp the intentions of the project.

**Comment by Prince07746** [comment]
Really, it is the first project I did too after my journey machine learning
at worldquant  , it's really amazing that you found it useful

**Comment by ceasor-elvis** [comment]
Glad you like it!
The reason is my career interest is being an ML engineer so I currently
love working with data

**Pull request merged**
